from __future__ import annotations

import pytest

from rvw.adjudicate import AdjudicationOutcome
from rvw.discover import EnrichedFinding, LaneCoverage, RunCoverage
from rvw.merge import merge
from rvw.presentation import PresentationConfig
from rvw.publication import render_publication
from rvw.schema import Severity, Tier, Verdict


def publication_fixture(locale: str = "ko"):
    body = (
        "스키마 검증 경계를 우회합니다\n\n검증 없이 잘못된 데이터가 저장됩니다. 저장 전에 스키마 검증을 적용하세요."
        if locale == "ko"
        else "Schema validation is bypassed\n\nInvalid data can be stored. Validate the schema before saving."
    )
    findings = [
        EnrichedFinding(
            rule_id=f"bori/schema-sot-bypass-{i}",
            file=f"src/item{i}.py",
            line=10 + i,
            hunk_id=f"hunk-{i}",
            severity=severity,
            body=body,
            anchorable=True,
            lane_id="lane",
            replica=1,
        )
        for i, severity in enumerate(
            [
                Severity.BLOCKER,
                Severity.WARNING,
                Severity.WARNING,
                Severity.BLOCKER,
                Severity.WARNING,
            ]
        )
    ]
    merged = merge(findings, lane_tiers={"lane": Tier.BASE})
    verdicts = {
        group.key: (
            Verdict.REJECTED
            if group.file == "src/item3.py"
            else Verdict.UNCERTAIN
            if group.file == "src/item4.py"
            else Verdict.CONFIRMED
        )
        for group in merged.groups
    }
    outcome = AdjudicationOutcome(
        verdicts=verdicts,
        reasons={
            key: (
                "저장 경로에서 검증을 수행하도록 수정하세요."
                if locale == "ko"
                else "Validate the data in the save path."
            )
            for key in verdicts
        },
        evidence={key: "save(unchecked_data)" for key in verdicts},
        replica_votes={key: [value] * 3 for key, value in verdicts.items()},
        unresolved=[key for key, value in verdicts.items() if value is Verdict.UNCERTAIN],
        coerced_rejections=1,
    )
    coverage = [
        LaneCoverage(
            lane_id="lane",
            dispatched=1,
            valid=1,
            findings=5,
            runs=[RunCoverage(replica=1, chunk=1, valid=True, findings=5, invalid_reason=None)],
            uncovered=["uncovered-hunk"],
        )
    ]
    return merged, outcome, coverage


@pytest.mark.parametrize("locale", ["ko", "en"])
def test_publication_mixed_fixture_keeps_human_evidence_only(locale):
    merged, outcome, coverage = publication_fixture(locale)
    result = render_publication(
        merged=merged,
        outcome=outcome,
        coverage=coverage,
        presentation=PresentationConfig(locale=locale),
    )
    for forbidden in [
        "Finding ID",
        "SHA",
        "/3",
        "rvw-",
        "build",
        "generated by",
        "report --synthesis",
        "src/item3.py",
        "uncovered-hunk",
        *[g.key for g in merged.groups],
    ]:
        assert forbidden not in result
    assert "`bori/schema-sot-bypass-0`" in result
    assert "src/item0.py:10" in result
    assert result.count("```\nsave(unchecked_data)\n```") == 4
    if locale == "ko":
        assert [
            result.index(s) for s in ["## 종합", "## 수정 필요", "## 확인 필요", "## 검증 미확정"]
        ] == sorted(
            result.index(s) for s in ["## 종합", "## 수정 필요", "## 확인 필요", "## 검증 미확정"]
        )
        assert "검토되지 않은 변경 구간이 1곳 있습니다." in result
    else:
        assert all(
            s in result
            for s in [
                "## Summary",
                "## Changes required",
                "## Needs attention",
                "## Verification uncertain",
            ]
        )
        assert "1 changed regions were not reviewed." in result


def test_publication_omits_empty_uncertainty_and_escapes_plain_footer():
    merged = merge([], lane_tiers={})
    result = render_publication(
        merged=merged,
        outcome=None,
        presentation=PresentationConfig(footer="A *plain* footer"),
    )
    assert "Verification uncertain" not in result
    assert r"A \*plain\* footer" in result
