from __future__ import annotations

import pytest

from rvw.adjudicate import AdjudicationOutcome
from rvw.discover import EnrichedFinding, LaneCoverage, RunCoverage
from rvw.i18n import t
from rvw.langgate import check_language
from rvw.merge import merge
from rvw.presentation import PresentationConfig
from rvw.publication import failed_lane_ids, publication_summary, render_publication
from rvw.schema import Severity, Tier, Verdict


def publication_fixture(locale: str = "ko"):
    body = (
        "스키마 검증 경계를 우회합니다\n\n검증 없이 잘못된 데이터가 저장됩니다. 저장 전에 스키마 검증을 적용하세요."
        if locale == "ko"
        else "Schema validation is bypassed\n\nInvalid data can be stored. Validate the schema before saving."
    )
    findings = [
        EnrichedFinding(
            rule_id=f"bori/schema-sot-bypass-{i}",
            file=f"src/item{i}.py",
            line=10 + i,
            hunk_id=f"hunk-{i}",
            severity=severity,
            body=body,
            anchorable=True,
            lane_id="lane",
            replica=1,
        )
        for i, severity in enumerate(
            [
                Severity.BLOCKER,
                Severity.WARNING,
                Severity.WARNING,
                Severity.BLOCKER,
                Severity.WARNING,
            ]
        )
    ]
    merged = merge(findings, lane_tiers={"lane": Tier.BASE})
    verdicts = {
        group.key: (
            Verdict.REJECTED
            if group.file == "src/item3.py"
            else Verdict.UNCERTAIN
            if group.file == "src/item4.py"
            else Verdict.CONFIRMED
        )
        for group in merged.groups
    }
    outcome = AdjudicationOutcome(
        verdicts=verdicts,
        reasons={
            key: (
                "저장 경로에서 검증을 수행하도록 수정하세요."
                if locale == "ko"
                else "Validate the data in the save path."
            )
            for key in verdicts
        },
        evidence={key: "save(unchecked_data)" for key in verdicts},
        replica_votes={key: [value] * 3 for key, value in verdicts.items()},
        unresolved=[key for key, value in verdicts.items() if value is Verdict.UNCERTAIN],
        coerced_rejections=1,
    )
    coverage = [
        LaneCoverage(
            lane_id="lane",
            dispatched=1,
            valid=1,
            findings=5,
            runs=[RunCoverage(replica=1, chunk=1, valid=True, findings=5, invalid_reason=None)],
            uncovered=["uncovered-hunk"],
        )
    ]
    return merged, outcome, coverage


@pytest.mark.parametrize("locale", ["ko", "en"])
def test_publication_mixed_fixture_keeps_human_evidence_only(locale):
    merged, outcome, coverage = publication_fixture(locale)
    result = render_publication(
        merged=merged,
        outcome=outcome,
        coverage=coverage,
        presentation=PresentationConfig(locale=locale),
    )
    for forbidden in [
        "Finding ID",
        "SHA",
        "/3",
        "rvw-",
        "build",
        "generated by",
        "report --synthesis",
        "src/item3.py",
        "uncovered-hunk",
        *[g.key for g in merged.groups],
    ]:
        assert forbidden not in result
    assert "`bori/schema-sot-bypass-0`" in result
    assert "src/item0.py:10" in result
    assert result.count("```\nsave(unchecked_data)\n```") == 4
    if locale == "ko":
        assert [
            result.index(s) for s in ["## 종합", "## 수정 필요", "## 확인 필요", "## 검증 미확정"]
        ] == sorted(
            result.index(s) for s in ["## 종합", "## 수정 필요", "## 확인 필요", "## 검증 미확정"]
        )
        assert "검토되지 않은 변경 구간이 1곳 있습니다." in result
    else:
        assert all(
            s in result
            for s in [
                "## Summary",
                "## Changes required",
                "## Needs attention",
                "## Verification uncertain",
            ]
        )
        assert "Changed regions not reviewed: 1." in result


def degraded_coverage() -> list[LaneCoverage]:
    def dead(lane_id: str, first_reason: str) -> LaneCoverage:
        return LaneCoverage(
            lane_id=lane_id,
            dispatched=1,
            valid=0,
            findings=0,
            runs=[
                RunCoverage(
                    replica=1,
                    chunk=1,
                    valid=False,
                    findings=0,
                    invalid_reason="exit_nonzero:124",
                    attempts=[
                        {
                            "attempt": 1,
                            "wave": "initial",
                            "valid": False,
                            "invalid_reason": first_reason,
                            "wall_seconds": 600.1,
                        },
                        {
                            "attempt": 2,
                            "wave": "retry",
                            "valid": False,
                            "invalid_reason": "exit_nonzero:124",
                            "wall_seconds": 600.1,
                        },
                    ],
                )
            ],
            redispatch_skipped="dead_by_timeout",
            uncovered=["src/app.py@@-0,0+1,2@@"],
        )

    healthy = LaneCoverage(
        lane_id="contracts",
        dispatched=1,
        valid=1,
        findings=0,
        runs=[RunCoverage(replica=1, chunk=1, valid=True, findings=0, invalid_reason=None)],
    )
    return [dead("correctness", "exit_nonzero:124"), dead("hygiene", "exit_nonzero:1"), healthy]


@pytest.mark.parametrize(
    ("locale", "expected"),
    [
        (
            "ko",
            "검토되지 않은 변경 구간이 1곳 있습니다. 검토를 완료하지 못한 규칙 묶음 2개: correctness, hygiene.",
        ),
        (
            "en",
            "Changed regions not reviewed: 1. Rule sets that did not finish: 2 (correctness, hygiene).",
        ),
    ],
)
def test_publication_summary_names_unfinished_rule_sets_verbatim(locale, expected):
    merged = merge([], lane_tiers={})
    presentation = PresentationConfig(locale=locale)
    summary = publication_summary(merged, None, degraded_coverage(), presentation)
    assert summary.endswith(expected)
    assert failed_lane_ids(degraded_coverage()) == ["correctness", "hygiene"]

    body = render_publication(
        merged=merged, outcome=None, coverage=degraded_coverage(), presentation=presentation
    )
    assert expected in body
    # The Latin lane identifiers are data; protected, the Korean body still passes the gate.
    assert check_language(body, locale, protected_literals=["correctness", "hygiene"])


def test_publication_summary_omits_the_sentence_when_every_lane_finished():
    merged = merge([], lane_tiers={})
    coverage = [degraded_coverage()[2]]
    for locale in ("ko", "en"):
        summary = publication_summary(merged, None, coverage, PresentationConfig(locale=locale))
        assert "correctness" not in summary
        assert summary == t("pub.completed", locale, b=0, w=0)


def test_publication_omits_empty_uncertainty_and_escapes_plain_footer():
    merged = merge([], lane_tiers={})
    result = render_publication(
        merged=merged,
        outcome=None,
        presentation=PresentationConfig(footer="A *plain* footer"),
    )
    assert "Verification uncertain" not in result
    assert r"A \*plain\* footer" in result


def test_korean_publication_fixture_passes_only_its_configured_locale():
    merged, outcome, coverage = publication_fixture("ko")
    result = render_publication(
        merged=merged,
        outcome=outcome,
        coverage=coverage,
        presentation=PresentationConfig(locale="ko"),
    )
    assert check_language(result, "ko")
    assert not check_language(result, "en")
