"""Deterministic file-first Markdown reporting for stacked PR reviews."""

from __future__ import annotations

from collections.abc import Sequence

from rvw import __version__
from rvw.stack import FindingLineage, MemberRunRef, StackManifest


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _state_label(lineage: FindingLineage) -> str:
    if lineage.state_pr is None:
        return lineage.state.value
    return f"{lineage.state.value} #{lineage.state_pr}"


def render_stack_report(
    manifest: StackManifest,
    member_runs: Sequence[MemberRunRef],
    lineages: Sequence[FindingLineage],
) -> str:
    """Render PR-local ordinary results and cross-head lineage history separately."""

    run_by_pr = {item.pr_number: item for item in member_runs}
    lines = [
        "# rvw stacked PR 리뷰",
        "",
        f"Stack run ID: `{manifest.run_id}`",
        f"Repository: `{manifest.repo}`",
        f"Tip: PR #{manifest.members[-1].number} @ `{manifest.members[-1].head_sha}`",
        "",
        "## 스택 멤버",
        "",
        "| PR | Title | Base | Head |",
        "| ---: | --- | --- | --- |",
    ]
    lines.extend(
        (
            f"| [#{member.number}]({member.url}) | {_cell(member.title)} | "
            f"`{member.base_ref}` / `{member.base_sha}` | "
            f"`{member.head_ref}` / `{member.head_sha}` |"
        )
        for member in manifest.members
    )
    lines.extend(["", "## PR별 로컬 리뷰"])
    for member in manifest.members:
        run = run_by_pr.get(member.number)
        lines.extend(["", f"### PR #{member.number} 로컬 결과", ""])
        if run is None:
            lines.append("ordinary review artifact missing")
            continue
        lines.extend(
            [
                f"Run: `{run.run_id}`",
                f"Report: `{run.report_path}`",
                "",
                "| Verdict | Count |",
                "| --- | ---: |",
                f"| CONFIRMED | {run.verdict_counts['CONFIRMED']} |",
                f"| REJECTED | {run.verdict_counts['REJECTED']} |",
                f"| UNCERTAIN | {run.verdict_counts['UNCERTAIN']} |",
            ]
        )

    lines.extend(["", "## Stack tip 발견 계보", ""])
    if not lineages:
        lines.append("추적할 actionable finding이 없습니다.")
    for lineage in lineages:
        location = f"{lineage.file}:{lineage.line if lineage.line is not None else 'unknown'}"
        pr_timeline = " → ".join(
            f"PR #{observation.pr_number}" for observation in lineage.observations
        )
        presence_timeline = " → ".join(
            observation.presence.value for observation in lineage.observations
        )
        lines.extend(
            [
                f"### {_state_label(lineage)} — `{lineage.rule_id}`",
                "",
                f"- Lineage: `{lineage.lineage_id}`",
                f"- Origin: PR #{lineage.origin_pr}, run `{lineage.origin_run_id}`, "
                f"finding `{lineage.origin_finding_id}`",
                f"- Origin location: `{location}`",
                f"- Severity: `{lineage.severity.value}`",
                f"- PR timeline: {pr_timeline}",
                f"- Presence: {presence_timeline}",
                "",
                "#### 원본 claim",
                "",
                *lineage.bodies,
                "",
                "#### Head별 근거",
                "",
                "| PR | Presence | Votes | Reason | Evidence |",
                "| ---: | --- | --- | --- | --- |",
            ]
        )
        lines.extend(
            (
                f"| #{observation.pr_number} | {observation.presence.value} | "
                f"{_cell(', '.join(vote.value for vote in observation.replica_votes) or '—')} | "
                f"{_cell(observation.reason or '—')} | {_cell(observation.evidence or '—')} |"
            )
            for observation in lineage.observations
        )
        lines.append("")

    lines.extend(["---", "", f"Generated by rvw {__version__}."])
    return "\n".join(lines).rstrip() + "\n"


__all__ = ["render_stack_report"]
